#########################################################################
# Micro-Server
# Copyright MXDeploy   2016
# All Rights Reserved.
# Author:    Fabio Santos B. da Silva
# Version:   0.0.1
# Date:      07/05/2016
# Purpose:   Deployment Suite and Automation
# URL :      www.mxdeploy.org
#########################################################################

---
# Playbook
name: Hello Playbook
thread-name: playbook-thread

variables:
  - name: message
    value: localhost

arguments:
  - name: username
    required: true

  - name: password
    required: true
    password: true

jobs:
  - name: Job 01
    src: ${modules.basedir}/hello/HelloAgain.py

  - name: Job 02
    src: ${modules.basedir}/hello/JobGroovy.groovy

...