#########################################################################
# Micro-Server
# Copyright MXDeploy   2016
# All Rights Reserved.
# Author:    Fabio Santos B. da Silva
# Version:   0.0.1
# Date:      07/05/2016
# Purpose:   Deployment Suite and Automation
# URL :      www.mxdeploy.org
#########################################################################

---
# Playbook
name: Playbook Hello Jython

vars:
  - hosts:
      - localhost

tasks:
  - name: Hello-01
    src: ${modules.basedir}/hello/Hello.py

...