#!/usr/bin/env bash
umask 002
debug=0
#########################################################################
# MXDeploy
# Copyright MXDeploy   2016
# All Rights Reserved.
# Author:    Fabio Santos B. da Silva
# Version:   0.0.1
# Date:      07/05/2016
# Purpose:   Deployment Suite and Automation
# URL :      www.mxdeploy.com
#########################################################################

debug(){
    if [ $debug != 0 ]; then
        echo "DEBUG: $1"
    fi
}

error(){
    echo ""
    echo "Error: $1"
    echo ""
}

validateYml(){
    YML=$1
    if [ ! -f  "$YML" ]; then
       echo "Error: The file $YML doesn't exist"
       exit
    fi
}

start_server(){
    MSERVER_NAME=$1
#    MX_PID_NAME=$2
    echo "==== Check micro-server $MSERVER_NAME status"
    SERVER_STATUS=0
#    PID=`cat $MX_PID_NAME`
    STATUS=`ps -ef | grep -v grep | grep $MSERVER_NAME | wc -l`
    if [ $STATUS -eq 1 ]; then
        echo "-------- $MSERVER_NAME is already up and running"
        SERVER_STATUS=1
    else
        echo "-------- $MSERVER_NAME is down"
    fi

    if [[ $SERVER_STATUS == 0 ]]; then
        echo "==== Starting $MSERVER_NAME"
        MX_JAVA_PROPERTIES="$MX_JAVA_PROPERTIES -Dmserver.name=$MSERVER_NAME "

        debug "$MX_JAVA -server $MX_JAVA_OPTION $MX_JAVA_PROPERTIES -cp $MX_JAVA_CLASSPATH/* org.mx.server.MicroServerGateway "
        nohup $MX_JAVA -server $MX_JAVA_OPTION $MX_JAVA_PROPERTIES \
                  -cp "$MX_JAVA_CLASSPATH/*" \
                   org.mx.server.MicroServerGateway  \
                   > /dev/null 2>&1 & echo $! > $MX_PID_NAME

        #$MX_JAVA -server $MX_JAVA_OPTION $MX_JAVA_PROPERTIES \
        #           -cp "$MX_JAVA_CLASSPATH/*" \
        #           org.mx.server.MicroServerGateway

        sleep 1
        PID=`cat $MX_PID_NAME`
        STATUS=`ps -ef | grep -v grep | grep $PID | wc -l`
        if [ $STATUS -eq 0 ]; then
            echo "-------- Error: Micro-Server $MSERVER_NAME wasn't started up, please validate"
            echo "  "
            exit
        else
            echo "-------- PID $PID"
            echo "  "
        fi
    fi
}

restart_server(){
    MSERVER_NAME=$1
#    MX_PID_NAME=$2
    echo "==== Check micro-server $MSERVER_NAME status"
    SERVER_STATUS=0
#    PID=`cat $MX_PID_NAME`
    STATUS=`ps -ef | grep -v grep | grep $MSERVER_NAME | wc -l`
    if [ $STATUS -eq 1 ]; then
        echo "-------- $MSERVER_NAME is up and running"
        SERVER_STATUS=1
    else
        echo "-------- $MSERVER_NAME is already down"
    fi

    if [[ $SERVER_STATUS == 1 ]]; then
        echo "==== Stopping $MSERVER_NAME"
        MX_JAVA_PROPERTIES_CLIENT="$MX_JAVA_PROPERTIES_CLIENT -Dmclient.chunktype=0 -Dmserver.name=$MSERVER_NAME"
        debug "MX_JAVA_PROPERTIES=$MX_JAVA_PROPERTIES_CLIENT"

        $MX_JAVA -server $MX_JAVA_OPTION $MX_JAVA_PROPERTIES_CLIENT \
                  -cp "$MX_JAVA_CLASSPATH/*" \
                   org.mx.client.MicroClient
    fi

    sleep 2
#    PID=`cat $MX_PID_NAME`
    STATUS=`ps -ef | grep -v grep | grep $MSERVER_NAME | wc -l`
    if [ $STATUS -eq 1 ]; then
        echo "-------- Micro-Server $MSERVER_NAME wasn't stopped, please validate."
        echo "  "
        exit
    else
        echo "-------- Micro-Server $MSERVER_NAME was shutdown"
        echo "==== Starting $MSERVER_NAME"
        MX_JAVA_PROPERTIES="$MX_JAVA_PROPERTIES -Dmserver.name=$MSERVER_NAME "
        debug "$MX_JAVA -server $MX_JAVA_OPTION $MX_JAVA_PROPERTIES -cp $MX_JAVA_CLASSPATH/* org.mx.server.MicroServerGateway "
        nohup $MX_JAVA -server $MX_JAVA_OPTION $MX_JAVA_PROPERTIES \
                  -cp "$MX_JAVA_CLASSPATH/*" \
                   org.mx.server.MicroServerGateway  \
                   > /dev/null 2>&1 & echo $! > $MX_PID_NAME
        sleep 1
        PID=`cat $MX_PID_NAME`
        STATUS=`ps -ef | grep -v grep | grep $PID | wc -l`
        if [ $STATUS -eq 0 ]; then
            echo "-------- Error: Micro-Server $MSERVER_NAME wasn't started up, please validate"
            exit
        else
            echo "-------- PID $PID"
        fi
    fi
}

run(){
    echo "===== Executing micro-action $ACTION_NAME"
    MX_JAVA_PROPERTIES_CLIENT="$MX_JAVA_PROPERTIES_CLIENT -Dmaction.name=$ACTION_NAME -Dmclient.chunktype=1 "
    if [ "$MCLIENT_NAME" != "x" ]; then
        MX_JAVA_PROPERTIES_CLIENT="$MX_JAVA_PROPERTIES_CLIENT -Dmclient.name=$MCLIENT_NAME "
    fi
    debug "MX_JAVA_PROPERTIES_CLIENT=$MX_JAVA_PROPERTIES_CLIENT"

    $MX_JAVA -server $MX_JAVA_OPTION $MX_JAVA_PROPERTIES_CLIENT \
              -cp "$MX_JAVA_CLASSPATH/*" \
               org.mx.client.MicroClient $*
}

if [ $# -eq 0 ]; then
   echo "Error : Argument doesn't exist. "
   echo "   Examples : mxd --start  "
   echo "              mxd --stop "
   echo "              mxd --restart "
   echo "              mxd --status "
   echo "              mxd --sessionExec <action-name> "
   exit
fi


PRG="$0"

# need this for relative symlinks
while [ -h "$PRG" ] ; do
    ls=`ls -ld "$PRG"`
    link=`expr "$ls" : '.*-> \(.*\)$'`
    if expr "$link" : '/.*' > /dev/null; then
        PRG="$link"
    else
        PRG="`dirname "$PRG"`/$link"
    fi
done

#MX_PARENT=`echo $PRG | sed 's|/mxd||g'`
MX_PARENT="/opt/mxdeploy"
MX_HOME="$MX_PARENT/micro-server"

debug "PRG: $PRG"
debug "MX_PARENT: $MX_PARENT"
debug "MX_HOME: $MX_HOME"

validateYml "$MX_PARENT/micro-env-variables.yml"
validateYml "$MX_HOME/micro-servers.yml"

MX_VERSION=`grep version $MX_HOME/version.yml | cut -d':' -f2 | xargs`
echo "+---------------------------------------------------------------------+"
echo "+  Micro-Server v"$MX_VERSION
echo "+---------------------------------------------------------------------+"

MX_JAVA_CLASSPATH="$MX_HOME/src/main/resources"
MX_JAVA_OPTION="-Xms128m -Xmx512m"
debug "MX_JAVA_OPTION=$MX_JAVA_OPTION"
MX_JAVA=$JAVA_HOME/bin/java
STATUS="0"

if [ "x$JAVA_HOME" == "x" ]; then
    #echo "  The property's content in mx.java.home=$MX_JAVA_HOME doesn't exist"
    #echo "  Please make are sure that are you using Java 1.8 and set up thin within $MX_DEPLOY_YML"
    #echo "  Lets try to use the current JAVA_HOME set up for SO"
    MX_JAVA="java"
fi

export JRUBY_OPTS="-J-Dlog4j.debug=true -J-Dlog4j.configuration=file:$MX_HOME/src/main/resources/log4j.properties"

MX_JAVA_PROPERTIES="-Dparent.basedir=$MX_PARENT "
debug "MX_JAVA_PROPERTIES=$MX_JAVA_PROPERTIES"

MX_JAVA_PROPERTIES_CLIENT="-Dparent.basedir=$MX_PARENT "
MCLIENT_NAME="x"
SCRIPT_ACTION="--list-threads"
MSERVER_NAME=`grep mserver.name: $MX_PARENT/micro-env-variables.yml | cut -d':' -f2 | xargs`
RESTART_ACTION="None"
ACTION_MODULE="None"
ARGS="None"
START_ARGS=0

while [ $# -gt 0 ]
do
    debug "SHIFT: $1"
    case $1 in
        --server|-s)
            MSERVER_NAME=$2
            debug "MSERVER_NAME: $MSERVER_NAME"
            shift
            ;;
        --client|-c)
            MCLIENT_NAME=$2
            debug "MCLIENT_NAME: $MCLIENT_NAME"
            shift
            ;;
        --start)
            SCRIPT_ACTION="--start"
            debug "SCRIPT_ACTION: $SCRIPT_ACTION"
            ;;
        --stop )
            SCRIPT_ACTION="--stop"
            debug "SCRIPT_ACTION: $SCRIPT_ACTION"
            ;;
        --restart )
            SCRIPT_ACTION="--restart"
            debug "SCRIPT_ACTION: $SCRIPT_ACTION"
            ;;
        --status )
            SCRIPT_ACTION="--status"
            debug "SCRIPT_ACTION: $SCRIPT_ACTION"
            ;;
        --list-threads | -lth )
            SCRIPT_ACTION="--list-threads"
            debug "SCRIPT_ACTION: $SCRIPT_ACTION"
            ;;
        --run | -r )
            SCRIPT_ACTION="--run"
            ACTION_NAME=$2
            START_ARGS=1
            debug "ACTION_NAME: $ACTION_NAME"
            shift
            ;;
        --restart-run | -rr )
            SCRIPT_ACTION="--restart-run"
            ACTION_NAME=$2
            START_ARGS=1
            debug "ACTION_NAME: $ACTION_NAME"
            shift
            ;;
        --module | -m )
            ACTION_MODULE=$2
            debug "ACTION_MODULE: $ACTION_MODULE"
            ;;
         * )
            debug "ARGUMENT: $1"
            if [ $START_ARGS -eq 1 ]; then
                if [ $ARGS == "None" ]
                then
                    debug "ARGS: $ARGS"
                    ARGS=$1
                else
                    ARGS="$ARGS $1"
                    debug "ARGS: $ARGS"
                fi
            fi
            ;;
    esac
    shift
done

MX_PID_NAME="$MX_HOME/logs/$MSERVER_NAME.pid"
debug "MX_PID_NAME: $MX_PID_NAME"

case "$SCRIPT_ACTION" in
    --start)
        start_server $MSERVER_NAME
        ;;
    --stop)
        echo "==== Stopping $MSERVER_NAME"
        MX_JAVA_PROPERTIES_CLIENT="$MX_JAVA_PROPERTIES_CLIENT -Dmclient.chunktype=0 -Dmserver.name=$MSERVER_NAME"
        debug "MX_JAVA_PROPERTIES=$MX_JAVA_PROPERTIES_CLIENT"

        $MX_JAVA -server $MX_JAVA_OPTION $MX_JAVA_PROPERTIES_CLIENT \
                  -cp "$MX_JAVA_CLASSPATH/*" \
                   org.mx.client.MicroClient

        sleep 2
#        PID=`cat $MX_PID_NAME`
        STATUS=`ps -ef | grep -v grep | grep $MSERVER_NAME | wc -l`
        if [ $STATUS -eq 1 ]; then
            echo "==== Micro-Server $MSERVER_NAME wasn't stopped, please validate."
            echo "  "
            exit
        else
            echo "==== Micro-Server $MSERVER_NAME was shutdown"
            echo "  "
            exit
        fi

        ;;
    --restart)
        restart_server $MSERVER_NAME
        RESTART_ACTION="--restart"
        ;;
    --status)
        debug "STATUS"
#        PID=`cat $MX_PID_NAME`
        STATUS=`ps -ef | grep -v grep | grep $MSERVER_NAME | wc -l`
        if [ $STATUS -eq 1 ]; then
            echo "===== $MX_MSERVER_NAME is up and running"
            #echo "  PID $PID"
        else
            echo "===== $MX_MSERVER_NAME is down"
            echo "  "
        fi

        ;;
    --run )
        start_server $MSERVER_NAME
        echo "+---------------------------------------------------------------------+"
        echo "===== Executing micro-action $ACTION_NAME"
        MX_JAVA_PROPERTIES_CLIENT="$MX_JAVA_PROPERTIES_CLIENT -Dmaction.name=$ACTION_NAME -Dmclient.chunktype=1 "
        if [ "$MCLIENT_NAME" != "x" ]; then
            MX_JAVA_PROPERTIES_CLIENT="$MX_JAVA_PROPERTIES_CLIENT -Dmclient.name=$MCLIENT_NAME "
        fi

        if [ "$ACTION_MODULE" != "None" ]; then
            MX_JAVA_PROPERTIES_CLIENT="$MX_JAVA_PROPERTIES_CLIENT -Dmodule.name=$ACTION_MODULE "
        fi
        debug "MX_JAVA_PROPERTIES_CLIENT=$MX_JAVA_PROPERTIES_CLIENT"
        debug "$MX_JAVA -server $MX_JAVA_OPTION $MX_JAVA_PROPERTIES_CLIENT -cp "$MX_JAVA_CLASSPATH/*" org.mx.client.MicroClient $ARGS"

        $MX_JAVA -server $MX_JAVA_OPTION $MX_JAVA_PROPERTIES_CLIENT \
                  -cp "$MX_JAVA_CLASSPATH/*" \
                   org.mx.client.MicroClient $ARGS

        ;;
    --restart-run )
        restart_server $MSERVER_NAME
        echo "+---------------------------------------------------------------------+"
        echo "===== Executing micro-action $ACTION_NAME"
        MX_JAVA_PROPERTIES_CLIENT="$MX_JAVA_PROPERTIES_CLIENT -Dmaction.name=$ACTION_NAME -Dmclient.chunktype=1 "
        if [ "$MCLIENT_NAME" != "x" ]; then
            MX_JAVA_PROPERTIES_CLIENT="$MX_JAVA_PROPERTIES_CLIENT -Dmclient.name=$MCLIENT_NAME "
        fi

        if [ "$ACTION_MODULE" != "None" ]; then
            MX_JAVA_PROPERTIES_CLIENT="$MX_JAVA_PROPERTIES_CLIENT -Dmodule.name=$ACTION_MODULE "
        fi

        debug "MX_JAVA_PROPERTIES_CLIENT=$MX_JAVA_PROPERTIES_CLIENT"
        debug "$MX_JAVA -server $MX_JAVA_OPTION $MX_JAVA_PROPERTIES_CLIENT -cp "$MX_JAVA_CLASSPATH/*" org.mx.client.MicroClient $ARGS"

        $MX_JAVA -server $MX_JAVA_OPTION $MX_JAVA_PROPERTIES_CLIENT \
                  -cp "$MX_JAVA_CLASSPATH/*" \
                   org.mx.client.MicroClient $ARGS

        ;;

    --list-threads )

        MX_JAVA_PROPERTIES_CLIENT="$MX_JAVA_PROPERTIES_CLIENT -Dmclient.chunktype=2 "
        if [ "$MCLIENT_NAME" != "x" ]; then
            MX_JAVA_PROPERTIES_CLIENT="$MX_JAVA_PROPERTIES_CLIENT -Dmclient.name=$MCLIENT_NAME "
        fi
        debug "MX_JAVA_PROPERTIES=$MX_JAVA_PROPERTIES_CLIENT"

        $MX_JAVA -server $MX_JAVA_OPTION $MX_JAVA_PROPERTIES_CLIENT \
                  -cp "$MX_JAVA_CLASSPATH/*" \
                   org.mx.client.MicroClient

        ;;
esac


echo " "



